### ISSUE TITLE
Shelby Ltd. CI를 요구합니다.

### ISSUE THREAD

**Issue by jihogrammer** [ShelbyLimitedCompany/Library-Of-Alexandria#5]
![](https://play-lh.googleusercontent.com/u7kZycaF6HaQ4g2JeofDr7X22L2ylaLz58LaGhfJlDtc1woithZvvtB--LocqnhfiHtjjFgxJrz8qZQhA7c)
![](https://i.pinimg.com/736x/27/cd/cd/27cdcdbfd763bb561a6f0996efc515e6.jpg)

**Comment by jihogrammer** [comment]
@drather 혹시 White Mater 영입 건은 어떻게 진행되고 있나요?

**Comment by drather** [comment]
@jihogramer  현재 계약서 사인만 남겨두고 있는 상태입니다.

**Comment by jihogrammer** [comment]
![image](https://user-images.githubusercontent.com/75299843/179119699-270ddf22-b54b-465b-a73e-f0609fc554f9.png)

@drather 로고 간지나게 바꿔주세요,,,
